### ISSUE TITLE
Issue with adding profile

### ISSUE THREAD

**Issue by guhaanandhnec08** [meruff/trailhead-leaderboard#1]
@meruff  I tried adding my Trailhead profile Id '00550000006286eAAA'. This profile is public on the trailhead page. I tried with both 18char and 15char. 

15char seems to work as it is accepting the input and the popup disappears. But After that, the profile doesn't appear on the board. I tried refreshing and reopening the leadership URL in a separate browser but no luck. Can you please check. Thanks.

**Comment by meruff** [comment]
Hi @guhaanandhnec08. Thanks for bringing this to my attention. Looks like I never implemented the code in my Visualforce controller to handle custom URLs (redirects) on the profiles. I'll have to test this a bit more before pushing up to the repo, but you're on the leaderboard now. Thanks!

**Comment by guhaanandhnec08** [comment]
Awesome Thanks @meruff  👍
