### ISSUE TITLE
Trailhead Id

### ISSUE THREAD

**Issue by paddybutler** [meruff/trailhead-leaderboard#2]
It does not seem possible to get the Trailhead Id anymore as it only ever seems to display the custom url e.g. in my case - the id is pbutler
Is there another way to get the necessary ID?

**Comment by meruff** [comment]
Hey @paddybutler thanks for bringing this up. I had thought I added some handling for custom URLs, but let me take a look at it.

**Comment by meruff** [comment]
seems related to #1

**Comment by paddybutler** [comment]
I cant add my ID to the leaderboard as there is validation on the input - I guess to check that it is a valid Salesforce ID (but my input is pbutler and not a Salesforce ID)

**Comment by paddybutler** [comment]
Added a pull request with the changes I made to get it working

**Comment by meruff** [comment]
Fixed in 8d553aa.
