### ISSUE TITLE
Outdated Trailhead URL and Search Strings

### ISSUE THREAD

**Issue by cmac08** [meruff/trailhead-leaderboard#4]
First off, thanks so much for creating this project and sharing your code. I found it yesterday during my company's hackathon and tried to implement the leaderboard in our sandbox. I did have to update the Trailhead URL (it's now trailblazer.me) and the search strings for the badges, points, and rank in the populateAll() method for the PopulateTrailblazers class. Unfortunately, I was not successful in getting the response to parse correctly and wanted to make you aware. I'll keep working on it and try again. Or maybe others have come across this problem as well. 

Example of my updates: 
public static final String TRAILHEAD_URL = 'https://trailblazer.me';
HttpRequest req = new HttpRequest();
req.setEndpoint(TRAILHEAD_URL + '/id?uid=' + trailblazer.Profile_Id__c);

Withing the populateTrailblazer method:
tb.Badges__c = Decimal.valueOf(resBody.substringBetween('<span class="tds-tally__count tds-tally__count_success" xpath="1">', '</').replace(',', '').trim());

**Comment by meruff** [comment]
Hey @cmac08! Yea this has happened a few times over the past year or so. Salesforce keeps updating the site and changing URLs which breaks the controller code that parses the webpage. It looks like they've moved a lot of the data present in the page HTML into JavaScript that my Apex controller can't get at, effectively breaking this repo. I'll have to see if there is a different way to scrap data from Trailhead.

**Comment by meruff** [comment]
Specifically, they're using LWCs now on a Visualforce page with `lightning.out.js`. So inspecting the page source you can't see the HTML rendered by the child components.

**Comment by LinThaw** [comment]
Is there any other way to get data badges, points etc?
Thanks.

**Comment by thi19** [comment]
Is there any other form to get the points, badges and point?

**Comment by meruff** [comment]
There's not really a way to do so currently, as the trailhead API is not public.

**Comment by thi19** [comment]
I need to answer urgent. I developed a class name RESTGetHttpContentCallout that is called in batch, but as the change trailhead link not possible, because the res.getBody(HttpResponse) return only <html>. Is there a option to solution this?

**Comment by krankekatze** [comment]
I wrote a Node.js batch script that scrape data from Trailhead profile pages and update `Trailblazer__c` records.
The script doesn’t upsert `Badge__c` now.

https://github.com/krankekatze/trailhead-batch

**Comment by Patlatus** [comment]
I used to have some similar integration like implemented here, but since it has broken, I have built a custom app on heroku which provides public access to Trailhead API. However, it hangs for some user profiles (not sure why). While for the others it works just fine.

This is a hack implementation to get access to Trailhead API to get Trailhead user points and other attributes. Requests should be used in the form https://trailheadapi.herokuapp.com/?link=/id/userAlias

It is possible to deploy code to your own heroku instance https://github.com/Patlatus/Salesforce-Trailhead-Api-Hack

**Comment by meruff** [comment]
Update: I've started addressing this in another development branch at 7e672e4. As stated previously, I can't really continue calling out to Trailhead and scraping the page directly, but I've taken inspiration from @krankekatze  and @Patlatus above and created [a Golang app](https://github.com/meruff/go-trailhead-leaderboard-api) that runs on Heroku that acts as a middleware for the Trailhead API. I'm rewriting parts of the leaderboard to use this API to retrieve the data.

**Comment by meruff** [comment]
I've merged in my changes from the /go-trailhead-api-dev branch into /master. Using the new Golang app solves this issue. Closing this for now.
