### ISSUE TITLE
Empty body while getting badges from Trailhead

### ISSUE THREAD

**Issue by sanjayprajapat** [meruff/trailhead-leaderboard#6]
Hey Sir,

I am hitting callout on https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/sanjay07/badges or .../badges/superbadge
and gettting status code 200 and status OK .
But it 's response body is empty.

Thanks
Sanjay Prajapat

**Comment by meruff** [comment]
@sanjayprajapat please see [#13](https://github.com/meruff/go-trailhead-leaderboard-api/issues/13) on my leaderboard API repo. This repo is for the leaderboard UI. I've already logged this as an issue there. 

Trailhead constantly changes their website and I need to update the API repo manually to handle it. I haven't been able to do so nor have I looked into it yet so I don't know if it's still possible to access the data. I will be closing this issue in favor of the other one.
